// Code generated by mockery v1.0.0. DO NOT EDIT.

package grabx

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockGrabX is an autogenerated mock type for the GrabX type
type MockGrabX struct {
	mock.Mock
}

// Get provides a mock function with given fields: ctx, name
func (_m *MockGrabX) Get(ctx context.Context, name string) string {
	ret := _m.Called(ctx, name)

	var r0 string
	if rf, ok := ret.Get(0).(func(context.Context, string) string); ok {
		r0 = rf(ctx, name)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
